"""Translation coverage audit for te-pa.org's i18n files.

Walks every lang/*.json against the canonical lang/en.json and reports:
  - Keys present in en.json but missing from a translation
  - Keys present in a translation but not in en.json (drift)
  - Values that are identical to the English fallback (untranslated)
  - Empty / whitespace-only values (placeholder strings never filled in)

Writes the report to docs/i18n-audit.md and exits 0 (informational only).
Run via:  python3 scripts/audit-translations.py
"""
from __future__ import annotations
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LANG_DIR = REPO / "lang"
OUT = REPO / "docs" / "i18n-audit.md"

# Locale labels (matches generate_badges.py LOCALES + the rest of the i18n set).
LOCALE_LABELS = {
    "en": "English (canonical)",
    "mi": "te reo Māori",
    "sm": "Gagana Sāmoa",
    "pt": "Português",
    "gn": "Avañe'ẽ (Guaraní)",
    "ar": "العربية (Arabic)",
}


def flatten(obj, prefix=""):
    """Yield (dotted_key, value) for every leaf value in a nested dict/list."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            yield from flatten(v, f"{prefix}.{k}" if prefix else k)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            yield from flatten(v, f"{prefix}[{i}]")
    else:
        yield prefix, obj


def main() -> None:
    en_path = LANG_DIR / "en.json"
    if not en_path.exists():
        raise SystemExit(f"missing canonical {en_path}")
    en = json.loads(en_path.read_text())
    en_flat = dict(flatten(en))
    en_keys = set(en_flat.keys())

    lines: list[str] = []
    lines.append("# te-pa.org translation coverage audit\n")
    lines.append("> Generated by `scripts/audit-translations.py`. Re-run after editing any `lang/*.json` to refresh.\n")
    lines.append(f"Canonical reference: `lang/en.json` ({len(en_keys)} leaf keys)\n\n")
    lines.append("## Summary\n\n")
    lines.append("| Locale | Coverage | Missing | Drifted | Untranslated (==en) | Empty |\n")
    lines.append("|---|---:|---:|---:|---:|---:|\n")

    detailed: list[str] = []

    for path in sorted(LANG_DIR.glob("*.json")):
        code = path.stem
        if code == "en":
            continue
        label = LOCALE_LABELS.get(code, code)
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError as e:
            lines.append(f"| `{code}` ({label}) | **PARSE ERROR** | — | — | — | — |\n")
            detailed.append(f"## `{code}` ({label}) — parse error\n\n`{e}`\n")
            continue
        flat = dict(flatten(data))
        keys = set(flat.keys())

        missing = sorted(en_keys - keys)
        drifted = sorted(keys - en_keys)
        same_as_en = sorted(
            k for k in (en_keys & keys)
            if isinstance(en_flat[k], str) and isinstance(flat[k], str)
            and en_flat[k].strip() and en_flat[k].strip() == flat[k].strip()
        )
        empty = sorted(
            k for k in keys
            if isinstance(flat[k], str) and not flat[k].strip()
        )

        coverage = (len(en_keys & keys) / len(en_keys) * 100) if en_keys else 0
        lines.append(
            f"| `{code}` ({label}) | {coverage:.1f}% | {len(missing)} | "
            f"{len(drifted)} | {len(same_as_en)} | {len(empty)} |\n"
        )

        detailed.append(f"\n## `{code}` — {label}\n\n")
        detailed.append(f"**Coverage:** {coverage:.1f}%  ·  **Keys:** {len(keys)} / {len(en_keys)}\n\n")

        if missing:
            detailed.append(f"### Missing keys ({len(missing)})\n\n")
            detailed.append("Keys present in `en.json` but absent from this locale:\n\n")
            for k in missing[:50]:
                detailed.append(f"- `{k}` — en: `{repr(en_flat[k])[:120]}`\n")
            if len(missing) > 50:
                detailed.append(f"- … and {len(missing) - 50} more\n")
            detailed.append("\n")

        if drifted:
            detailed.append(f"### Drifted keys ({len(drifted)}) — exist here but not in en.json\n\n")
            for k in drifted[:30]:
                detailed.append(f"- `{k}`\n")
            if len(drifted) > 30:
                detailed.append(f"- … and {len(drifted) - 30} more\n")
            detailed.append("\n")

        if same_as_en:
            detailed.append(f"### Untranslated ({len(same_as_en)}) — value equals English\n\n")
            detailed.append("These may be intentional (proper nouns) but most should be translated:\n\n")
            for k in same_as_en[:30]:
                detailed.append(f"- `{k}` — `{repr(en_flat[k])[:120]}`\n")
            if len(same_as_en) > 30:
                detailed.append(f"- … and {len(same_as_en) - 30} more\n")
            detailed.append("\n")

        if empty:
            detailed.append(f"### Empty / whitespace-only ({len(empty)})\n\n")
            for k in empty[:30]:
                detailed.append(f"- `{k}`\n")
            if len(empty) > 30:
                detailed.append(f"- … and {len(empty) - 30} more\n")
            detailed.append("\n")

    lines.append("\n")
    lines.extend(detailed)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines))
    print(f"Wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
